importando bibliotecas e montando Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

ajustar o caminho da leitura do seu arquivo
importando o arquivo do pandas parquet

In [ ]:
df_bureau = pd.read_parquet('/content/drive/MyDrive/hackathon_pod_2025/database/raw/base_score_bureau_movel/base_score_bureau_movel/part-00000-b6bf6bdd-9a2d-4bc5-a97c-fa8553906bc9-c000.snappy.parquet')
df_bureau.head()

    SAFRA FLAG_INSTALACAO FPD PROD flag_mig2 SCORE_01 SCORE_02      NUM_CPF
0  202410               1   0  CMV       PRE      562      636  ZZZZZX7XWY8
1  202410               1   1  CMV       PRE      546      518  ZZZZZX88YXY
2  202410               1   0  CMV       PRE      621      750  ZZZZZYT7XYT
3  202410               1   1  CMV       PRE      609      679  ZZZZZNTXY9Z
4  202410               1   0  CMV       PRE      621      722  ZZZZZ79ZXUX

analisando como estao os dados

In [ ]:
df_bureau.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1290526 entries, 0 to 1290525
Data columns (total 8 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   SAFRA            1290526 non-null  object
 1   FLAG_INSTALACAO  1290526 non-null  object
 2   FPD              1290526 non-null  object
 3   PROD             1290526 non-null  object
 4   flag_mig2        1290526 non-null  object
 5   SCORE_01         1281087 non-null  object
 6   SCORE_02         1289950 non-null  object
 7   NUM_CPF          1290526 non-null  object
dtypes: object(8)
memory usage: 78.8+ MB

converter o dados para um tipo certo

In [ ]:
df_bureau['SAFRA']=df_bureau['SAFRA'].astype(int)
df_bureau['FLAG_INSTALACAO']=df_bureau['FLAG_INSTALACAO'].astype(int)
df_bureau['FPD']=df_bureau['FPD'].astype(int)
df_bureau['PROD']=df_bureau['PROD'].astype(str)
df_bureau['flag_mig2']=df_bureau['flag_mig2'].astype(str)
df_bureau['SCORE_01']=df_bureau['SCORE_01'].astype(float)
df_bureau['SCORE_02']=df_bureau['SCORE_02'].astype(float)
df_bureau['NUM_CPF']=df_bureau['NUM_CPF'].astype(str)

In [ ]:
df_bureau.describe()

              SAFRA  FLAG_INSTALACAO           FPD      SCORE_01      SCORE_02
count  1.290526e+06        1290526.0  1.290526e+06  1.281087e+06  1.289950e+06
mean   2.024555e+05              1.0  2.357147e-01  5.869004e+02  6.275538e+02
std    4.546795e+01              0.0  4.244449e-01  5.748067e+01  9.607562e+01
min    2.024100e+05              1.0  0.000000e+00  0.000000e+00  1.000000e+00
25%    2.024110e+05              1.0  0.000000e+00  5.540000e+02  5.570000e+02
50%    2.024120e+05              1.0  0.000000e+00  5.870000e+02  6.220000e+02
75%    2.025020e+05              1.0  0.000000e+00  6.210000e+02  6.960000e+02
max    2.025030e+05              1.0  1.000000e+00  7.780000e+02  9.170000e+02

In [ ]:
df_bureau.shape

(1290526, 8)

iniciar uma analise dos dados !

In [ ]:
df_bureau['FPD'].value_counts(normalize=True)

FPD
0    0.764285
1    0.235715
Name: proportion, dtype: float64